export type PaymentProvider = 'stripe' | 'ramp' | 'transak' | 'paystack'

interface CurrencyConfig {
  code: string
  name: string
  providers: PaymentProvider[]
}

export const currencyOptions: CurrencyConfig[] = [
    /*{ code: 'USD', name: 'US Dollar', providers: ['stripe', 'ramp', 'transak'] },
    { code: 'EUR', name: 'Euro', providers: ['stripe', 'transak'] },
    { code: 'GBP', name: 'British Pound', providers: ['stripe', 'transak'] },*/
    { code: 'NGN', name: 'Nigerian Naira', providers: ['paystack'] },
    /*{ code: 'INR', name: 'Indian Rupee', providers: ['transak'] },
    { code: 'AUD', name: 'Australian Dollar', providers: ['stripe'] },
    { code: 'CAD', name: 'Canadian Dollar', providers: ['stripe', 'transak'] },
    { code: 'JPY', name: 'Japanese Yen', providers: ['stripe', 'transak'] },
    { code: 'CNY', name: 'Chinese Yuan', providers: ['transak'] },
    { code: 'MXN', name: 'Mexican Peso', providers: ['stripe', 'transak'] },
    { code: 'BRL', name: 'Brazilian Real', providers: ['stripe', 'ramp'] },
    { code: 'ZAR', name: 'South African Rand', providers: ['paystack'] },
    { code: 'SAR', name: 'Saudi Riyal', providers: ['stripe'] },
    { code: 'SGD', name: 'Singapore Dollar', providers: ['stripe'] },
    { code: 'SEK', name: 'Swedish Krona', providers: ['stripe', 'transak'] },
    { code: 'CHF', name: 'Swiss Franc', providers: ['stripe'] },
    { code: 'NOK', name: 'Norwegian Krone', providers: ['stripe'] },
    { code: 'DKK', name: 'Danish Krone', providers: ['stripe'] },
    { code: 'MYR', name: 'Malaysian Ringgit', providers: ['stripe'] },
    { code: 'PHP', name: 'Philippine Peso', providers: ['paystack'] },
    { code: 'PLN', name: 'Polish Zloty', providers: ['stripe', 'transak'] },
    { code: 'THB', name: 'Thai Baht', providers: ['stripe'] },
    { code: 'IDR', name: 'Indonesian Rupiah', providers: ['transak'] },
    { code: 'HUF', name: 'Hungarian Forint', providers: ['stripe', 'transak'] },
    { code: 'CZK', name: 'Czech Koruna', providers: ['stripe', 'transak'] },
    { code: 'ILS', name: 'Israeli New Shekel', providers: ['stripe', 'transak'] },
    { code: 'KWD', name: 'Kuwaiti Dinar', providers: ['stripe'] },
    { code: 'BHD', name: 'Bahraini Dinar', providers: ['stripe'] },
    { code: 'OMR', name: 'Omani Rial', providers: ['stripe'] },
    { code: 'QAR', name: 'Qatari Rial', providers: ['stripe'] },
    { code: 'AED', name: 'United Arab Emirates Dirham', providers: ['stripe'] },
    { code: 'VND', name: 'Vietnamese Dong', providers: ['transak'] },
    { code: 'EGP', name: 'Egyptian Pound', providers: ['paystack'] },
    { code: 'KZT', name: 'Kazakhstani Tenge', providers: ['transak'] },
    { code: 'UZS', name: 'Uzbekistani Som', providers: ['transak'] },
    { code: 'KRW', name: 'South Korean Won', providers: ['stripe', 'transak'] },
    { code: 'CLP', name: 'Chilean Peso', providers: ['transak'] },
    { code: 'COP', name: 'Colombian Peso', providers: ['stripe'] },
    { code: 'PEN', name: 'Peruvian Nuevo Sol', providers: ['stripe'] },
    { code: 'BBD', name: 'Barbadian Dollar', providers: ['stripe'] },
    { code: 'TWD', name: 'New Taiwan Dollar', providers: ['stripe', 'transak'] },
    { code: 'KHR', name: 'Cambodian Riel', providers: ['transak'] },
    { code: 'GHS', name: 'Ghanaian Cedi', providers: ['paystack'] },
    { code: 'TZS', name: 'Tanzanian Shilling', providers: ['paystack'] },
    { code: 'KES', name: 'Kenyan Shilling', providers: ['paystack'] },
    { code: 'AFN', name: 'Afghan Afghani', providers: ['paystack'] },
    { code: 'LKR', name: 'Sri Lankan Rupee', providers: ['paystack'] },
    { code: 'MKD', name: 'Macedonian Denar', providers: ['stripe'] },
    { code: 'RSD', name: 'Serbian Dinar', providers: ['stripe'] },
    { code: 'MDL', name: 'Moldovan Leu', providers: ['stripe'] },
    { code: 'HRK', name: 'Croatian Kuna', providers: ['stripe'] },
    { code: 'UAH', name: 'Ukrainian Hryvnia', providers: ['stripe'] },
    { code: 'RON', name: 'Romanian Leu', providers: ['stripe'] },
    { code: 'SYP', name: 'Syrian Pound', providers: ['stripe'] },
    { code: 'JMD', name: 'Jamaican Dollar', providers: ['stripe'] },
    { code: 'BSD', name: 'Bahamian Dollar', providers: ['stripe'] },
    { code: 'KGS', name: 'Kyrgyzstani Som', providers: ['stripe'] },
    { code: 'MNT', name: 'Mongolian Tugrik', providers: ['stripe'] },
    { code: 'KYD', name: 'Cayman Islands Dollar', providers: ['stripe'] },
    { code: 'BMD', name: 'Bermudian Dollar', providers: ['stripe'] },
    { code: 'VUV', name: 'Vanuatu Vatu', providers: ['stripe'] },
    { code: 'XPF', name: 'CFP Franc', providers: ['stripe'] },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra', providers: ['stripe'] },
    { code: 'BIF', name: 'Burundian Franc', providers: ['stripe'] },
    { code: 'GNF', name: 'Guinean Franc', providers: ['stripe'] },
    { code: 'MWK', name: 'Malawian Kwacha', providers: ['paystack'] },
    { code: 'LSL', name: 'Lesotho Loti', providers: ['stripe'] },
    { code: 'MRO', name: 'Mauritanian Ouguiya', providers: ['stripe'] },
    { code: 'DJF', name: 'Djiboutian Franc', providers: ['stripe'] },
    { code: 'SLL', name: 'Sierra Leonean Leone', providers: ['stripe'] },
    { code: 'AWG', name: 'Aruban Florin', providers: ['stripe'] },
    { code: 'SRD', name: 'Surinamese Dollar', providers: ['stripe'] },
    { code: 'GMD', name: 'Gambian Dalasi', providers: ['stripe'] },
    { code: 'FJD', name: 'Fijian Dollar', providers: ['stripe'] },
    { code: 'SBD', name: 'Solomon Islands Dollar', providers: ['stripe'] },
    { code: 'PAB', name: 'Panamanian Balboa', providers: ['stripe'] },
    { code: 'PYG', name: 'Paraguayan Guarani', providers: ['stripe'] },
    { code: 'HTG', name: 'Haitian Gourde', providers: ['stripe'] },
    { code: 'CUC', name: 'Cuban Convertible Peso', providers: ['stripe'] },
    { code: 'SVC', name: 'Salvadoran Colón', providers: ['stripe'] },
    { code: 'BZD', name: 'Belize Dollar', providers: ['stripe'] },
    { code: 'GWP', name: 'Guinea-Bissau Peso', providers: ['stripe'] },
    { code: 'NIO', name: 'Nicaraguan Córdoba', providers: ['stripe'] },
    { code: 'GTQ', name: 'Guatemalan Quetzal', providers: ['stripe'] },
    { code: 'BRB', name: 'Barbadian Dollar', providers: ['stripe'] },
    { code: 'CUP', name: 'Cuban Peso', providers: ['stripe'] },
    { code: 'SHP', name: 'Saint Helena Pound', providers: ['stripe'] },
    { code: 'MMK', name: 'Myanmar Kyat', providers: ['transak'] },
    { code: 'MUR', name: 'Mauritian Rupee', providers: ['stripe'] },
    { code: 'UGX', name: 'Ugandan Shilling', providers: ['paystack'] },
    { code: 'MDG', name: 'Malagasy Ariary', providers: ['paystack'] },
    { code: 'BDT', name: 'Bangladeshi Taka', providers: ['paystack'] },*/
  ]
  
